Repository codestates-seb/seb39_main_040, pull requests merged in 2022-09, with the labels that each got.

#38 (FE) 헤더, 카페아이템 컴포넌트 마크업 진행
  client/package-lock.json
  client/package.json
  client/src/components/Header.jsx
  client/src/components/cafe/CafeItem.jsx
Labels: FE: 조은영, 마크업

#37 (FE) 탭 컴포넌트 마크업 및 기능 구현
  client/src/App.jsx
  client/src/components/README.md
  client/src/components/cafe/CafeDetailTab.jsx
  client/src/components/cafe/CafeImagesTab.jsx
  client/src/components/cafe/CafeInfo.jsx
  client/src/components/cafe/CafeReviewsTab.jsx
  client/src/components/tab/CafeTab.jsx
  client/src/components/tab/CafeTabContent.jsx
  client/src/pages/CafePage.jsx
Labels: 📌기능, FE: 홍성아, 마크업

#52 [FE] 마이페이지, 로그인, 회원가입 페이지 마크업
  client/package-lock.json
  client/package.json
  client/src/components/cafe/CafeItem.jsx
  client/src/components/login/LoginForm.jsx
  client/src/components/login/SignUpForm.jsx
  client/src/components/mypage/ReviewItem.jsx
  client/src/components/mypage/myPageDetailTab/MyPageInfoTab.jsx
  client/src/components/mypage/myPageDetailTab/MyPageReviewTab.jsx
  client/src/components/mypage/myPageDetailTab/MyPageWishTab.jsx
  client/src/components/ui/Header.jsx
  client/src/components/ui/MainTitle.jsx
  client/src/components/ui/myPageTab/MyPageTab.jsx
  client/src/components/ui/myPageTab/MyPageTabContent.jsx
  client/src/pages/Login.jsx
  client/src/pages/Mypage.jsx
  client/src/pages/SignUp.jsx
  client/src/styles/GlobalStyle.jsx
Labels: FE: 조은영

#53 [FE] 메인페이지, 리뷰작성 페이지 마크업
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.jsx
  client/src/components/cafe/CafeListItem.jsx
  client/src/components/cafe/cafeDetailTab/CafeDetailTab.jsx
  client/src/components/cafe/cafeDetailTab/CafeImagesTab.jsx
  client/src/components/cafe/cafeDetailTab/CafeInfo.jsx
  client/src/components/cafe/cafeDetailTab/CafeReviewImage.jsx
  client/src/components/cafe/cafeDetailTab/CafeReviewItem.jsx
  client/src/components/cafe/cafeDetailTab/CafeReviewsTab.jsx
  client/src/components/cafe/cafeMain/Filter.jsx
  client/src/components/cafe/cafeMain/Search.jsx
  client/src/components/cafe/cafeMain/TagCategory.jsx
  client/src/components/map/CafeDetailMap.jsx
  client/src/components/review/ ReviewForm.jsx
  client/src/components/review/ImageUpload.jsx
  client/src/components/ui/Button.jsx
  client/src/components/ui/MainTitle.jsx
  client/src/components/ui/cafeTab/CafeTab.jsx
  client/src/pages/CafePage.jsx
  client/src/pages/EditReviewPage.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/NewReviewPage.jsx
  client/src/pages/README.md
  client/src/styles/GlobalStyle.jsx
Labels: FE: 홍성아, 💅스타일, 마크업

#54 [FE] 각 페이지 라우터 연결
  client/src/App.jsx
  client/src/components/cafe/cafeDetailTab/CafeReviewsTab.jsx
  client/src/components/mypage/ReviewItem.jsx
  client/src/components/review/ReviewForm.jsx
  client/src/components/ui/Header.jsx
  client/src/components/ui/MainTitle.jsx
  client/src/pages/EditReviewPage.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/NewReviewPage.jsx
Labels: ⚒️설정, FE

#60 [FE] 회원가입, 로그인 유효성 검사 & 나의정보 탭 구조조정
  client/src/components/login/LoginForm.jsx
  client/src/components/login/SignUpForm.jsx
  client/src/components/mypage/myPageDetailTab/MyPageInfoTab.jsx
  client/src/pages/Login.jsx
  client/src/pages/SignUp.jsx
Labels: FE

#65 [FE] 유저수정페이지 마크업 & 로그인 페이지 수정
  client/src/App.jsx
  client/src/components/mypage/myPageDetailTab/MyPageInfoTab.jsx
  client/src/pages/Login.jsx
  client/src/pages/UserUpdate.jsx
Labels: 📌기능, FE: 조은영, 💅스타일, 마크업

#70 [FE] refactor: 프로젝트 파일 리팩토링
  client/src/App.jsx
  client/src/components/cafe/CafeCard.jsx
  client/src/components/cafe/CafeCards.jsx
  client/src/components/cafe/CafeInfo.jsx
  client/src/components/cafe/CafePageBottomSection/CafeDetailInfo/CafeDetailInfoMap.jsx
  client/src/components/cafe/CafePageBottomSection/CafeDetailInfo/index.jsx
  client/src/components/cafe/CafePageBottomSection/CafePhotos/CafePhotoCard.jsx
  client/src/components/cafe/CafePageBottomSection/CafePhotos/CafePhotoCards.jsx
  client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCard.jsx
  client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCards.jsx
  client/src/components/cafe/cafeDetailTab/CafeDetailTab.jsx
  client/src/components/cafe/cafeMain/Search.jsx
  client/src/components/common/Button.jsx
  client/src/components/common/Header.jsx
  client/src/components/common/MainTitle.jsx
  client/src/components/mypage/UserReviewCard.jsx
  client/src/components/mypage/UserReviewCards.jsx
  client/src/components/mypage/myPageDetailTab/MyPageWishTab.jsx
  client/src/components/review/EditReviewForm.jsx
  client/src/components/review/NewReviewForm.jsx
  client/src/components/ui/cafeTab/CafeTabContent.jsx
  client/src/components/ui/myPageTab/MyPageTabContent.jsx
  client/src/pages/CafeDetail/CafeInfoPage.jsx
  client/src/pages/CafeDetail/CafePhotoPage.jsx
  client/src/pages/CafeDetail/CafeReviewPage.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/Review/EditReviewPage.jsx
  client/src/pages/Review/NewReviewPage.jsx
  client/src/pages/SignUpPage.jsx
  client/src/pages/User/UserInfoEditPage.jsx
  client/src/pages/User/UserInfoPage.jsx
  client/src/pages/User/UserReviewPage.jsx
  client/src/pages/User/UserWishPage.jsx
  client/src/utils/README.md
Labels: FE, 🔃 리팩토링

#71 [BE] 오타 수정
  server/src/main/java/seb39_40/coffeewithme/user/controller/UserController.java
  server/src/main/java/seb39_40/coffeewithme/user/service/UserService.java
Labels: 🐞버그, BE

#74 (#20)refactor:카페상세페이지 마크업 리팩토링
  client/src/App.jsx
  client/src/components/cafe/CafeInfo.jsx
  client/src/components/cafe/CafePageBottomSection/CafeDetailInfo/index.jsx
  client/src/components/cafe/CafePageBottomSection/CafeMenu/index.jsx
  client/src/components/cafe/CafePageBottomSection/CafePhotos/CafePhotoCard.jsx
  client/src/components/cafe/CafePageBottomSection/CafePhotos/CafePhotoCards.jsx
  client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCard.jsx
  client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCards.jsx
  client/src/components/cafe/CafePageTopSection/CafeInfoMap.jsx
  client/src/components/cafe/CafePageTopSection/index.jsx
  client/src/components/cafe/cafeDetailTab(toDelete)/CafeDetailTab.jsx
  client/src/components/cafe/cafeDetailTab(toDelete)/CafeReviewsTab.jsx
  client/src/components/cafe/cafeDetailTab/CafeImagesTab.jsx
  client/src/components/cafe/cafeDetailTab/CafeReviewImage.jsx
  client/src/components/cafe/cafeDetailTab/CafeReviewItem.jsx
  client/src/components/cafe/cafeMain/Filter.jsx
  client/src/components/cafe/cafeMain/Search.jsx
  client/src/components/cafe/cafeMain/TagCategory.jsx
  client/src/components/common/Button.jsx
  client/src/components/common/MainTitle.jsx
  client/src/components/common/TabBar.jsx
  client/src/components/common/Tag.jsx
  client/src/components/common/Title.jsx
  client/src/components/review/EditImageUpload.jsx
  client/src/components/review/EditReviewForm.jsx
  client/src/components/review/ReviewForm.jsx
  client/src/components/review/ReviewImageUpload.jsx
  client/src/components/review/ReviewStarRating.jsx
  client/src/components/review/ReviewTag.jsx
  client/src/components/ui/cafeTab/CafeTab.jsx
  client/src/pages/CafeDetail/CafeMenuPage.jsx
  client/src/pages/CafeDetail/CafePhotoPage.jsx
  client/src/pages/CafeDetail/CafeReviewPage.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/Review/EditReviewPage.jsx
  client/src/pages/Review/NewReviewPage.jsx
  client/src/pages/User/UserInfoPage.jsx
  client/src/styles/GlobalStyle.jsx
Labels: 🔃 리팩토링, FE: 홍성아, 💅스타일, 마크업

#75 [FE] 각 페이지, 컴포넌트 리팩토링
  client/src/assets/CoffeeWithMe.svg
  client/src/assets/README.md
  client/src/assets/title1.svg
  client/src/components/common/Header.jsx
  client/src/components/common/Title.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/SignUpPage.jsx
  client/src/styles/GlobalStyle.jsx
Labels: FE: 조은영

#79 [FE] 중간 제목 컴포넌트 구현
  client/src/components/common/MiddleTitle.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/SignUpPage.jsx
  client/src/pages/User/UserInfoPage.jsx
Labels: 📌기능, FE: 조은영, 마크업

#84 (#51)refactor: 메인페이지 마크업 리팩토링
  client/src/App.jsx
  client/src/components/cafe/CafeCard.jsx
  client/src/components/cafe/CafeCards.jsx
  client/src/components/common/Button.jsx
  client/src/components/common/FilterBar.jsx
  client/src/components/common/MiddleTitle.jsx
  client/src/components/common/ScrollToTop.jsx
  client/src/components/common/SearchBar.jsx
  client/src/components/common/Tag.jsx
  client/src/components/review/ReviewForm.jsx
  client/src/components/review/ReviewImageUpload.jsx
  client/src/components/review/ReviewStarRating.jsx
  client/src/components/ui/cafeTab/CafeTabContent.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/Review/EditReviewPage.jsx
  client/src/pages/Review/NewReviewPage.jsx
Labels: 🔃 리팩토링, FE: 홍성아, 💅스타일, 마크업

#85 [FE] 회원가입, 로그인 기능 구현
  client/src/components/common/Header.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/SignUpPage.jsx
  client/src/store/useAuth.jsx
Labels: FE: 조은영

#95 [FE] 로그인 상태 전역 관리 설정
  client/src/components/common/Header.jsx
  client/src/components/mypage/UserReviewCard.jsx
  client/src/components/mypage/UserReviewCards.jsx
  client/src/components/mypage/UserWishCard.jsx
  client/src/components/mypage/UserWishCards.jsx
  client/src/components/mypage/myPageDetailTab/MyPageInfoTab.jsx
  client/src/components/mypage/myPageDetailTab/MyPageReviewTab.jsx
  client/src/components/mypage/myPageDetailTab/MyPageWishTab.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/SignUpPage.jsx
  client/src/pages/User/UserInfoEditPage.jsx
  client/src/pages/User/UserInfoPage.jsx
  client/src/pages/User/UserReviewPage.jsx
  client/src/pages/User/UserWishCard.jsx
  client/src/pages/User/UserWishPage.jsx
  client/src/store/useAuth.jsx
  client/src/store/useLoginStore.jsx
Labels: 🔃 리팩토링, FE: 조은영

#102 [FE] 찜한카페 & 유저리뷰 구현 및 코드 수정
  client/src/components/common/Header.jsx
  client/src/components/mypage/ReviewItem.jsx
  client/src/components/mypage/UserReviewCard.jsx
  client/src/components/mypage/UserReviewCards.jsx
  client/src/components/mypage/UserWishCard.jsx
  client/src/components/mypage/UserWishCards.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/User/UserInfoEditPage.jsx
  client/src/pages/User/UserInfoPage.jsx
  client/src/pages/User/UserReviewPage.jsx
  client/src/pages/User/UserWishCard.jsx
  client/src/store/useAuth.jsx
Labels: FE: 조은영

#103 [FE] 로그인 상태 저장명 변경
  client/src/store/useLoginStore.jsx
Labels: 📌기능, FE: 조은영

#105 (#100)feat: 이미지첨부기능구현
  client/src/components/review/NewReviewForm.jsx
Labels: 📌기능, FE: 홍성아

#115 (#110)feat: 이미지 첨부 기능 수정
  client/public/coffeefavicon.ico
  client/public/index.html
  client/src/components/review/NewReviewForm.jsx
Labels: 📌기능, FE: 홍성아, 마크업

#116 [FE] 로그아웃, 푸터 구현 및 axios interceptors 생성
  client/src/api/core.jsx
  client/src/components/common/Footer.jsx
  client/src/components/common/Header.jsx
  client/src/pages/User/UserInfoEditPage.jsx
  client/src/pages/User/UserInfoPage.jsx
  client/src/store/useAuth.jsx
Labels: FE: 조은영
