Repository codestates-seb/seb39_main_040, pull requests merged in 2022-10, with the labels that each got.

#126 (#110)이미지첨부 미리보기 기능 구현
  client/public/index.html
  client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCard.jsx
  client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCards.jsx
  client/src/components/cafe/CafePageTopSection/CafeInfoMap.jsx
  client/src/components/common/ErrorAlert.jsx
  client/src/components/common/SuccessAlert.jsx
  client/src/components/review/NewReviewForm.jsx
Labels: 📌기능, FE: 홍성아

#127 [FE] 위시리스트 추가/삭제 구현
  client/src/components/mypage/UserWishCard.jsx
  client/src/components/mypage/UserWishCards.jsx
Labels: 📌기능, FE: 조은영

#129 [FE] 프로필 사진 추가 구현
  client/src/api/core.jsx
  client/src/components/cafe/CafeItem.jsx
  client/src/components/cafe/CafePageTopSection/index.jsx
  client/src/components/common/Header.jsx
  client/src/components/mypage/UserReviewCard.jsx
  client/src/components/mypage/UserReviewCards.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/Review/EditReviewPage.jsx
  client/src/pages/User/UserInfoEditPage.jsx
  client/src/pages/User/UserInfoPage.jsx
  client/src/store/useAuth.jsx
Labels: 📌기능, 🔃 리팩토링, FE: 조은영

#130 (#114)feat: 주소를 좌표로 변경해 마커표시 기능구현
  client/public/index.html
  client/src/components/cafe/CafePageTopSection/CafeInfoMap.jsx
  client/src/components/cafe/CafePageTopSection/index.jsx
  client/src/components/review/NewReviewForm.jsx
Labels: 📌기능, FE: 홍성아

#131 [FE] 유저 정보 수정 구현
  client/src/api/core.jsx
  client/src/components/common/Header.jsx
  client/src/pages/User/UserInfoEditPage.jsx
  client/src/pages/User/UserInfoPage.jsx
Labels: FE: 조은영

#132 [FE] 리뷰 수정&삭제 구현
  client/src/components/mypage/UserReviewCard.jsx
  client/src/components/review/EditReviewForm.jsx
  client/src/pages/Review/EditReviewPage.jsx
Labels: 📌기능, FE: 조은영

#133 [FE] 메인페이지 검색 기능 구현
  client/src/components/cafe/CafeCards.jsx
  client/src/components/common/SearchBar.jsx
  client/src/pages/MainPage.jsx
  client/src/store/search.jsx
Labels: 📌기능, FE: 조은영

#135 [FE] 사용하지 않는 코드&주석 제거
  client/package-lock.json
  client/package.json
  client/src/assets/Spinner.gif
  client/src/components/common/Header.jsx
  client/src/components/common/Loading.jsx
  client/src/components/common/SearchBar.jsx
  client/src/components/mypage/UserReviewCard.jsx
  client/src/components/mypage/UserWishCards.jsx
  client/src/components/review/EditReviewForm.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/Review/EditReviewPage.jsx
  client/src/pages/SignUpPage.jsx
Labels: FE: 조은영

#136 (#113)feat: 카테고리 필터링 기능 구현
  client/src/components/cafe/CafeCards.jsx
  client/src/components/common/FilterBar.jsx
  client/src/pages/MainPage.jsx
Labels: 📌기능, FE: 홍성아

#146 (#140)feat: 캐러셀 구현
  client/package-lock.json
  client/package.json
  client/src/assets/Carousel1.jpg
  client/src/assets/Carousel2.jpg
  client/src/assets/Carousel3.jpg
  client/src/components/cafe/CafePageBottomSection/CafePhotos/CafePhotoCard.jsx
  client/src/components/cafe/CafePageBottomSection/CafePhotos/CafePhotoCards.jsx
  client/src/components/common/Carousel.jsx
  client/src/components/common/TabBar.jsx
  client/src/components/common/Title.jsx
  client/src/pages/CafeDetail/CafeDetailPage.jsx
  client/src/pages/MainPage.jsx
Labels: 📌기능, FE: 홍성아

#147 [FE] 메인페이지 무한스크롤 구현
  client/src/assets/Spinner.gif
  client/src/components/cafe/CafeCards.jsx
  client/src/components/common/Loading.jsx
Labels: 📌기능, FE: 조은영

#148 [FE] 불필요한 코드 수정&알림창 수정
  client/src/api/core.jsx
  client/src/assets/Profile.jpeg
  client/src/components/common/Header.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/SignUpPage.jsx
  client/src/pages/User/UserInfoEditPage.jsx
Labels: 🔃 리팩토링, FE: 조은영

#149 (#141)feat: 관리자추천 뱃지 기능 구현
  client/src/assets/badge.svg
  client/src/components/cafe/CafePageTopSection/index.jsx
  client/src/pages/CafeDetail/CafeDetailPage.jsx
  client/src/styles/GlobalStyle.jsx
Labels: 📌기능, FE: 홍성아

#150 (#12)feat:css정리 및 alert창 조건부 추가
  client/src/components/cafe/CafeCard.jsx
  client/src/components/cafe/CafeCards.jsx
  client/src/components/cafe/CafePageBottomSection/CafeMenu/index.jsx
  client/src/components/cafe/CafePageBottomSection/CafePhotos/CafePhotoCard.jsx
  client/src/components/cafe/CafePageBottomSection/CafePhotos/CafePhotoCards.jsx
  client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCard.jsx
  client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCards.jsx
  client/src/components/cafe/CafePageTopSection/CafeInfoMap.jsx
  client/src/components/cafe/CafePageTopSection/index.jsx
  client/src/components/common/Button.jsx
  client/src/components/common/ErrorAlert.jsx
  client/src/components/common/FilterBar.jsx
  client/src/components/common/Footer.jsx
  client/src/components/common/Header.jsx
  client/src/components/common/MiddleTitle.jsx
  client/src/components/common/SearchBar.jsx
  client/src/components/common/SuccessAlert.jsx
  client/src/components/common/TabBar.jsx
  client/src/components/common/Tag.jsx
  client/src/components/review/EditReviewForm.jsx
  client/src/components/review/NewReviewForm.jsx
  client/src/components/review/ReviewImageUpload.jsx
  client/src/components/review/ReviewStarRating.jsx
  client/src/pages/CafeDetail/CafeDetailPage.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/Review/EditReviewPage.jsx
  client/src/pages/Review/NewReviewPage.jsx
Labels: 📌기능, FE: 홍성아, 💅스타일

#151 [FE] css 수정 및 alert 조건부 처리
  client/src/components/mypage/UserReviewCard.jsx
  client/src/components/mypage/UserReviewCards.jsx
  client/src/components/mypage/UserWishCard.jsx
  client/src/components/mypage/UserWishCards.jsx
  client/src/components/ui/myPageTab/MyPageTab.jsx
  client/src/components/ui/myPageTab/MyPageTabContent.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/SignUpPage.jsx
  client/src/pages/User/UserInfoEditPage.jsx
  client/src/pages/User/UserInfoPage.jsx
  client/src/pages/User/UserReviewPage.jsx
  client/src/pages/User/UserWishPage.jsx
  client/src/store/search.jsx
  client/src/store/useAuth.jsx
  client/src/store/useCafe.jsx
Labels: 📌기능, FE: 조은영, 💅스타일

#152 [FE] css 수정 & 로그아웃시 alert 창 수정
  client/src/components/common/Carousel.jsx
  client/src/components/common/Header.jsx
  client/src/pages/LoginPage.jsx
Labels: 📌기능, FE: 조은영, 💅스타일

#154 (#153)feat: 404에러페이지 구현
  client/src/App.jsx
  client/src/pages/NotFoundPage.jsx
Labels: 📌기능, FE: 홍성아, 마크업

#156 [FE] 코드 수정
  client/.gitignore
  client/public/index.html
  client/src/components/cafe/CafePageTopSection/index.jsx
  client/src/components/common/Header.jsx
Labels: 🐞버그, 📌기능, FE

#158 (#12)style:이미지첨부 css 수정
  client/src/components/review/EditReviewForm.jsx
  client/src/components/review/NewReviewForm.jsx
Labels: FE: 홍성아, 💅스타일

#160 (#12)style: 안내창추가작업
  client/src/components/cafe/CafeCards.jsx
Labels: FE: 홍성아, 💅스타일

#161 [FE] 찜한카페 하트 위치 조정
  client/src/components/mypage/UserWishCard.jsx
Labels: FE: 조은영, 💅스타일

#162 [FE] 같은데이터를 2번 불러오는 현상 제거
  client/src/components/cafe/CafeCards.jsx
Labels: 🐞버그, 📌기능, FE: 조은영

#164 (#12)feat&style:데이터조회기능 수정 및 css세부작업
  client/src/components/cafe/CafeCard.jsx
  client/src/components/cafe/CafeCards.jsx
  client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCards.jsx
  client/src/components/cafe/CafePageTopSection/CafeInfoMap.jsx
  client/src/components/cafe/CafePageTopSection/index.jsx
  client/src/pages/CafeDetail/CafeDetailPage.jsx
Labels: 📌기능, FE: 홍성아, 💅스타일

#165 [FE] css 수정 & 로그인 유저 대상으로만 찜하기 기능 사용 제한
  client/src/components/cafe/CafeCards.jsx
  client/src/components/cafe/CafePageTopSection/index.jsx
Labels: 📌기능, FE: 조은영, 💅스타일

#166 (#12)style: 폰트변경
  client/public/index.html
  client/src/styles/GlobalStyle.jsx
Labels: FE: 홍성아, 💅스타일

#170 (#12)feat: 상세데이터 조회 수정
  client/src/components/cafe/CafePageTopSection/index.jsx
Labels: 📌기능, FE: 홍성아

#171 [FE] 무한스크롤 버그, css 수정
  client/src/components/cafe/CafeCard.jsx
  client/src/components/cafe/CafeCards.jsx
  client/src/store/useCafe.jsx
Labels: 🐞버그, FE: 조은영, 💅스타일

#174 [FE] 무한스크롤 렌더링 과정 수정
  client/src/components/cafe/CafeCards.jsx
  client/src/pages/MainPage.jsx
Labels: 🐞버그, 📌기능, FE: 조은영

#177 [FE] merge: fe브랜치 -> dev브랜치로 merge
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.jsx
  client/src/api/core.jsx
  client/src/assets/Carousel1.jpg
  client/src/assets/Carousel2.jpg
  client/src/assets/Carousel3.jpg
  client/src/assets/Profile.jpeg
  client/src/assets/Spinner.gif
  client/src/assets/badge.svg
  client/src/components/cafe/CafeCard.jsx
  client/src/components/cafe/CafeCards.jsx
  client/src/components/cafe/CafePageBottomSection/CafeMenu/index.jsx
  client/src/components/cafe/CafePageBottomSection/CafePhotos/CafePhotoCard.jsx
  client/src/components/cafe/CafePageBottomSection/CafePhotos/CafePhotoCards.jsx
  client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCard.jsx
  client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCards.jsx
  client/src/components/cafe/CafePageTopSection/CafeInfoMap.jsx
  client/src/components/cafe/CafePageTopSection/index.jsx
  client/src/components/common/Button.jsx
  client/src/components/common/Carousel.jsx
  client/src/components/common/FilterBar.jsx
  client/src/components/common/Footer.jsx
  client/src/components/common/Header.jsx
  client/src/components/common/Loading.jsx
  client/src/components/common/MiddleTitle.jsx
  client/src/components/common/SearchBar.jsx
  client/src/components/common/TabBar.jsx
  client/src/components/common/Tag.jsx
  client/src/components/common/Title.jsx
  client/src/components/mypage/UserReviewCard.jsx
  client/src/components/mypage/UserReviewCards.jsx
  client/src/components/mypage/UserWishCard.jsx
  client/src/components/mypage/UserWishCards.jsx
  client/src/components/review/EditReviewForm.jsx
  client/src/components/review/NewReviewForm.jsx
  client/src/components/review/ReviewImageUpload.jsx
  client/src/components/review/ReviewStarRating.jsx
  client/src/components/ui/myPageTab/MyPageTab.jsx
  client/src/components/ui/myPageTab/MyPageTabContent.jsx
  client/src/pages/CafeDetail/CafeDetailPage.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/NotFoundPage.jsx
  client/src/pages/Review/EditReviewPage.jsx
  client/src/pages/Review/NewReviewPage.jsx
  client/src/pages/SignUpPage.jsx
  client/src/pages/User/UserInfoEditPage.jsx
  client/src/pages/User/UserInfoPage.jsx
  client/src/pages/User/UserReviewPage.jsx
  client/src/pages/User/UserWishPage.jsx
  client/src/store/useAuth.jsx
  client/src/store/useCafe.jsx
  client/src/styles/GlobalStyle.jsx
Labels: FE
